language: node_js
node_js:
  - "node"
  - "5.3"
  - "5.2"
  - "5.1"
  - "5.0"
  - "4.2.4"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
  - "iojs"
script: "npm run-script test-travis"
# Send coverage data to Coveralls
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
